default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: furima_39473_development

test:
  <<: *default
  database: furima_39473_test

production:
  <<: *default
  database: furima_39473_production
  username: furima_39473
  password: <%= ENV["FURIMA_39473_DATABASE_PASSWORD"] %>
